import type { Metadata } from 'next';
import { Geist, Geist_Mono, Tajawal } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from './providers/ReactQueryProvider';
import ToastsProvider from './providers/ToastsProvider';
import { ToastContainer } from 'react-toastify';

const tajawal = Tajawal({
  variable: '--font-tajawal',
  subsets: ['arabic', 'latin'],
  weight: ['400', '700'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <head>
        <link rel="icon" href="/images/logo.png" sizes="any" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tajawal.variable} antialiased`}
      >
        <ReactQueryProvider>
          {children}
          <ToastsProvider />
          <ToastContainer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
