export type InputTypes =
  | 'text'
  | 'password'
  | 'search'
  | 'number'
  | 'email'
  | 'phone'
  | 'tel'
  | 'select'
  | 'multi-select'
  | 'date'
  | 'radio'
  | 'file'
  | 'textarea'
  | 'checkbox';